[package]
name = "wasmiter"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
readme = "README.md"

[dependencies]
smallvec = { version = "1.10.0", optional = true, default-features = false, features = ["const_generics", "const_new", "union"] }
memmap2 = { version = "0.6.2", optional = true }

[features]
default = ["backtrace", "std", "mmap"]
alloc = ["smallvec"]
std = ["alloc"]
backtrace = ["std"]
mmap = ["std", "dep:memmap2"]

[dev-dependencies]
criterion = "0.4.0"
wat = "1.0.64"
insta = "1.29.0"

[[bench]]
name = "bytes"
harness = false

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
