[package]
name = "wasmiter"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"
readme = "README.md"

[features]
default = ["backtrace", "std"]
alloc = []
std = ["alloc"]
backtrace = ["std"]

[dev-dependencies]
criterion = "0.4.0"
wat = "1.0.64"

[[bench]]
name = "bytes"
harness = false
