[package]
name = "the_monster"
version.workspace = true
edition.workspace = true

[dependencies]
wasmiter = { workspace = true }
wat = "1.0.66"

[lib]
test = false
bench = false
crate-type = ["cdylib"]
